### ISSUE TITLE
Blynk Authentication Failure

### ISSUE THREAD

**Issue by ChuckGl** [hrafnkelle/tfbrew#7]
Don't know if you are still supporting tfbrew.  I just started encountering an issue.  TFBrew fails to connect to Blynk-Cloud. I tried researching it but I am out of my depths on this one.  I did try going back to older versions of Raspberry Pi and clean installs of TFBrew.  I think something changed at Blynk or perhaps in Python.  It was working about 3-4 weeks ago.  I brewed a nice Kveik Pseudo Lager.  The error being thrown is:

Using config from config.yaml
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
Blynk authentication failed
Blynk authentication failed
Blynk authentication failed
Blynk authentication failed
Fatal error: protocol.data_received() call failed.
protocol: <plugins.BlynkLib.BlynkProtocol object at 0xb59fef90>
transport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 813, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/home/pi/tfbrew/plugins/BlynkLib.py", line 201, in data_received
    self.run()
  File "/home/pi/tfbrew/plugins/BlynkLib.py", line 213, in run
    msg_type, msg_id, status = struct.unpack(HDR_FMT, data)
struct.error: unpack requires a buffer of 5 bytes
Blynk got connection lost
unpack requires a buffer of 5 bytes
NoneType: None

**Comment by ChuckGl** [comment]
Issue is on Blynk-cloud side.  Switching to IP for cloud server housing my project worked.
